site_name: Workshop on Responsible Digital Relationships
use_directory_urls: false
nav:
- 'Digital Devices & Networks':
    - 'Computer Networks':
        - 'The World Wide Web' : 'contents/devices/www.md'
- 'Digital Identity':
    - '0. Guide' : 'contents/digitalid/about.md'
    - '1. Understanding Digital Identity: What it is and why it is important': 'contents/digitalid/digitalid.md'
    - '2. Creating Online Personas: Choosing Usernames and Avatars': 'contents/digitalid/aliasavatar.md'
    - '3. How We See Ourselves and Others See Us Online: Self-image and Perception': 'contents/digitalid/selfconcept.md'
    - '4. People Who Influence Our Digital Identity': 'contents/digitalid/influencers.md'
    - '5. Leaving Our Mark Online: Digital Footprints and Online Reputation': 'contents/digitalid/footprint.md'
    - '6. Being a Responsible Digital Citizen': 'contents/digitalid/behaviours.md'
    - '7. Staying Safe Online: Protecting Our Personal Information and Privacy': 'contents/digitalid/privacy.md'
- 'Digital Relationships':
    #- 'Virtual and physical friendship.': ''
    #- 'Digital environments for social exchange and online games.': ''
    #- 'Strategies for an equal, safe, and healthy cyber coexistence. Digital etiquette.': ''
    #- 'Advantages and benefits of interactions in the digital environment.': ''    
    - 'IT Threats (I)':
        - 'Botnets' : 'contents/relationships/itthreats/botnets.md'
        - 'Hacking' : 'contents/relationships/itthreats/hacking.md'
        - 'Malware' : 'contents/relationships/itthreats/malware.md'
        - 'Pharming' : 'contents/relationships/itthreats/pharming.md'
        - 'Phishing' : 'contents/relationships/itthreats/phishing.md'
    - 'IT Threats (II)':
        - 'Ransomware' : 'contents/relationships/itthreats/ransomware.md'
        - 'SPAM' : 'contents/relationships/itthreats/spam.md'
        - 'Spoofing' : 'contents/relationships/itthreats/spoofing.md'
        - 'Spyware' : 'contents/relationships/itthreats/spyware.md'
    - 'IT Threats (III)':
        - 'Trojan Horse' : 'contents/relationships/itthreats/trojan.md'
        - 'Viruses' : 'contents/relationships/itthreats/virus.md'
        - 'WiFi Eavesdropping' : 'contents/relationships/itthreats/wifieavesdropping.md'
        - 'Worms' : 'contents/relationships/itthreats/worms.md'
        - 'Glossary' : 'contents/relationships/itthreats/glossary.md'
    - 'Tips for Online Safety and Privacy':
        - 'Tip 1: Think before you share' : 'contents/relationships/tips/thinkbefore.md'
        - 'Tip 2: Protect Your Stuff' : 'contents/relationships/tips/protectstuff.md'
        - 'Tip 3: Know & Use Your Settings' : 'contents/relationships/tips/knowsettings.md'
        - 'Tip 4: Avoid Scams' : 'contents/relationships/tips/avoidscams.md'
        - 'Tip 5: Be Positive' : 'contents/relationships/tips/bepositive.md'
        - 'Tip 6: Internet Safety and Privacy' : 'contents/relationships/tips/safetyprivacy.md'
    #- 'Addictions. Techno addiction, nomophobia, and online gambling addiction.': ''
#- 'Programación Didáctica':
#    - 'Elementos curriculares': 'pd/curriculo/curriculo.md'
theme:
    language: es
    name: 'readthedocs'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: Roboto
        code: Roboto Mono
    logo: 'images/floppy-ict1.png'

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - footnotes