site_name: Workshop on Responsible Digital Relationships
use_directory_urls: false
nav:
- '1. Digital Devices & Internet':
    - 'Introduction': 'contents/devices/intro.md'
    - '1.1. Personal computers, mobile devices, and other devices for domestic and educational use':
        - 'Introduction': 'contents/devices/s11_intro.md'
        - 'Personal computers': 'contents/devices/s11_personalcomputers.md'
        - 'Mobile devices': 'contents/devices/s11_mobiledev.md'
        - 'Other devices': 'contents/devices/s11_otherdev.md'
    - '1.2. Basic functioning and most important characteristics of digital devices':
        - 'Introduction': 'contents/devices/s12_intro.md'
        - 'What is a Digital Device?': 'contents/devices/digdev.md'
        - 'The CPU': 'contents/devices/s12_cpu.md'
        - 'Types of Memories': 'contents/devices/s12_memories.md'
        - 'Peripheral Devices': 'contents/devices/s12_peripheral.md'
    - '1.3. Common operating systems and applications':
        - 'Introduction': 'contents/devices/s13_intro.md'
        - 'Operating Systems': 'contents/devices/s13_os.md'
        - 'Applications': 'contents/devices/s13_apps.md'
    - '1.4. Device networks. Fundamentals and ways to access the Internet':
        - 'Introduction': 'contents/devices/s14_intro.md'
        - 'The World Wide Web' : 'contents/devices/s14_www.md'
    - '1.5. The digital divide':
        - 'What is Digital Divide?': 'contents/devices/s15_digitaldivide.md'
    - '1.6. Basic security habits to protect devices':
        - 'Introduction': 'contents/devices/s16_intro.md'
    - '1.7. Implications of the use of digital devices for health, sustainability, and the environment. Obsolescence':
        - 'Introduction': 'contents/devices/s17_intro.md'
        - 'Digital Devices and Health': 'contents/devices/s17_intro.md'
        - 'Sustainability and Environment': 'contents/devices/s17_intro.md'
        - 'Obsolescence': 'contents/devices/s17_intro.md'

- '2. Digital Content':
        - '0. Introduction' : 'contents/digitalcontents/intro.md'
        - '1. Types of web search engines and their filtering tools' : 'contents/digitalcontents/intro.md'
        - '2. Selecting information in digital media through web search engines, verifying its accuracy' : 'contents/digitalcontents/searchengines.md'
        - '3. Reading and interpreting information from digital media' : 'contents/digitalcontents/searchengines.md'
        - '4. Intellectual property and copyright' : 'contents/digitalcontents/searchengines.md'
        - '5. Detecting fake news, hoaxes, and hate speech. Social implications' : 'contents/digitalcontents/searchengines.md'
        - '6. Organization of information. Basic operations with files and folders' : 'contents/digitalcontents/searchengines.md'
        - '7. Customizing the work environment' : 'contents/digitalcontents/searchengines.md'
        - '8. Basic content creation with digital tools' : 'contents/digitalcontents/searchengines.md'
        - '9. Aesthetics and audiovisual language' : 'contents/digitalcontents/searchengines.md'
- 'Digital Identity':
    - '0. Guide' : 'contents/digitalid/about.md'
    - '1. Understanding Digital Identity: What it is and why it is important': 'contents/digitalid/digitalid.md'
    - '2. Creating Online Personas: Choosing Usernames and Avatars': 'contents/digitalid/aliasavatar.md'
    - '3. How We See Ourselves and Others See Us Online: Self-image and Perception': 'contents/digitalid/selfconcept.md'
    - '4. People Who Influence Our Digital Identity': 'contents/digitalid/influencers.md'
    - '5. Leaving Our Mark Online: Digital Footprints and Online Reputation': 'contents/digitalid/footprint.md'
    - '6. Being a Responsible Digital Citizen': 'contents/digitalid/behaviours.md'
    - '7. Staying Safe Online: Protecting Our Personal Information and Privacy': 'contents/digitalid/privacy.md'
    - '8. Fake News, Hate Speech, and Online Platforms': 'contents/digitalid/fakehateonline.md'

- 'Digital Relationships':
    #- 'Virtual and physical friendship.': ''
    #- 'Digital environments for social exchange and online games.': ''
    #- 'Strategies for an equal, safe, and healthy cyber coexistence. Digital etiquette.': ''
    #- 'Advantages and benefits of interactions in the digital environment.': ''    
    - 'IT Threats (I)':
        - 'Botnets' : 'contents/relationships/itthreats/botnets.md'
        - 'Hacking' : 'contents/relationships/itthreats/hacking.md'
        - 'Malware' : 'contents/relationships/itthreats/malware.md'
        - 'Pharming' : 'contents/relationships/itthreats/pharming.md'
        - 'Phishing' : 'contents/relationships/itthreats/phishing.md'
    - 'IT Threats (II)':
        - 'Ransomware' : 'contents/relationships/itthreats/ransomware.md'
        - 'SPAM' : 'contents/relationships/itthreats/spam.md'
        - 'Spoofing' : 'contents/relationships/itthreats/spoofing.md'
        - 'Spyware' : 'contents/relationships/itthreats/spyware.md'
    - 'IT Threats (III)':
        - 'Trojan Horse' : 'contents/relationships/itthreats/trojan.md'
        - 'Viruses' : 'contents/relationships/itthreats/virus.md'
        - 'WiFi Eavesdropping' : 'contents/relationships/itthreats/wifieavesdropping.md'
        - 'Worms' : 'contents/relationships/itthreats/worms.md'
        - 'Glossary' : 'contents/relationships/itthreats/glossary.md'
    - 'Tips for Online Safety and Privacy':
        - 'Tip 1: Think before you share' : 'contents/relationships/tips/thinkbefore.md'
        - 'Tip 2: Protect Your Stuff' : 'contents/relationships/tips/protectstuff.md'
        - 'Tip 3: Know & Use Your Settings' : 'contents/relationships/tips/knowsettings.md'
        - 'Tip 4: Avoid Scams' : 'contents/relationships/tips/avoidscams.md'
        - 'Tip 5: Be Positive' : 'contents/relationships/tips/bepositive.md'
        - 'Tip 6: Internet Safety and Privacy' : 'contents/relationships/tips/safetyprivacy.md'
    #- 'Addictions. Techno addiction, nomophobia, and online gambling addiction.': ''
#- 'Programación Didáctica':
#    - 'Elementos curriculares': 'pd/curriculo/curriculo.md'
theme:
    language: es
    name: 'readthedocs'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: Roboto
        code: Roboto Mono
    logo: 'images/floppy-ict1.png'

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - footnotes